on:
  schedule:
  - cron: '0 */12 * * *'
  workflow_dispatch:
name: Excavator
jobs:
  excavate:
    name: Excavate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Excavate
      uses: shovel-org/GithubActions@main
      env:
        GITH_EMAIL: rodrigost23@users.noreply.github.com
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SKIP_UPDATED: '1'
