on:
  schedule:
  - cron: '0 */12 * * *'
name: Excavator
jobs:
  excavate:
    name: Excavate
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: Excavate
      uses: ScoopInstaller/GithubActions@main
      env:
        USER_EMAIL: rodrigost23@users.noreply.github.com
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SKIP_UPDATED: '1'
